### ISSUE TITLE
Deal with referee report

### ISSUE THREAD

**Issue by will-henney** [JavGVastro/PhD.Paper#16]
We now have the referee report on the paper, which had only one comment that needs to be addressed: 

>  will be happy to recommend the manuscript for publication after some clarification of some details:
> 
> - To study the Finite box effects, as well as that of seeing the authors do an interesting exercise with idealized data (as fractional Brownian motion -fBm- 2D data modified to include a correlation taper).
> This approach is very clear, but there is one issue that requires attention, and that is that of the projection from a 3D field to a 2D field. 
> In reality the density/velocity fields are three-dimensional but some information is lost in the projection to a 2D map.
> 
> For the exercise presented in appendix A, the authors use a 2D map that was modified to include the proper spectral index (n_2D = m +2) and a correlation length r_0, in reality one would have a 3D map with a spectral index (n_3D = m +3), which if integrated along the line of sight would change the spectral index from n_3D to n_2D (and within the transition some inertial range could be 'lost') .
> 
> In other words in the current version of the paper the r_0 is entirely in the plane of the sky, while in reality should correspond to the 3D field, and at the same time the transition from a 3D to a 2D map could curve more the structure functions.
> I believe that it would be beneficial to obtain the 2D map from collapsing a 3D fBm (with an index m+3) and the same exponential taper used and verify that the main results hold, or discuss this an additional limitation.

**Comment by will-henney** [comment]
In order to deal with this, we need to generate a fake 3d velocity cube:

- [ ] Modify `make_3dfield()` to have ellipticity and also the tapered power law
- [ ] Use `make_3dfield()` to generate a 3d velocity field
- [ ] Use this velocity field, together with a uniform density field to generate a PPV cube using `make_ppv()`
- [ ] Apply the seeing to each velocity channel of the PPV cube
- [ ] Calculate the mean velocity map from the blurred PPV cube

Then we should look at the velocity maps to make sure they are OK.  Up to here can be in one notebook. We should save the velocity maps for each value of the seeing. 

From then on, the calculation of the structure function is the same as we had previously.

**Comment by will-henney** [comment]
Javier has finished an initial exploration of this in Fake-Maps/fake-3d-tapered-maps.ipynb

The results look promising. I just have a few queries:

- [ ] The smoothed channel maps have some problem at the edges, for instance:
![CleanShot 2023-01-28 at 20 04 35](https://user-images.githubusercontent.com/161264/215300378-085f8ce1-7512-46ca-be0d-d5b1f806a055.jpg)  But the smoothed moment1 maps do not seem to have this problem, so I am not sure what is going on.
- [ ] We need to check that the structure function slope is equal to m in the unsmoothed case. 
- [ ] It looks like the effect of seeing on the structure function is a bit less than what we found previously. It will be interesting to see if this is still true when we do the non-periodic maps

**Comment by will-henney** [comment]
Then the following steps will be:

- [ ] Repeat for the non-periodic case (512 cube, divided into 4).  I guess there is no problem with it still being periodic in the z axis
- [ ] We should also try the case of having a fluctuating emissivity (equivalent to density) field as well as velocity field. I would suggest doing this by generating a `log E` field in exactly the same way as the velocity field, and then taking the exponential of it to get the emissivity field.  The fractional std dev of the emissivity should be 2-3 times larger than the fractional std dev of the surface brightness (see Fig 15), so about 2. When we do this, we need to check carefully what the slope of the structure function is, since the projection smoothing will be less according to the arguments that we give in the discussion.

**Comment by JavGVastro** [comment]
I have made some progress on the analysis of smoothing the non-periodic first moment maps, but still are some points made by Dr. Will which should be adressed asap, among others.

1. In the notebook 'Fake-Maps/fake-3d-tapered-maps.ipynb' I added and initial exploration using the non-tapered map. In this case the non-tapered structure function slope is steeper than the one used as an input in the cration of the velocity fields. In the image below the structure functions with 'x' are normalized. So, im not sure at what extent this will be a problem in our analysis.

![firefox_XH1GIWYao9](https://user-images.githubusercontent.com/53878105/215798246-8c85372e-f1ad-4b20-8fe0-4adb67f659d9.png)

2. The creation of the non-periodic smoothed maps (512 cube) and the calculation of the structure functions are made in the notebooks 'fake-3d-maps-seeing-nonp-create' and  'fake-3d-maps-seeing-nonp-sosf-computation', respectively, and their respective results are exported: 'v_maps_3ds.json' for the first moment maps and 'fake-tapered-3d-nonp-nn-s0-000-00-strucfunc.json'  for each division with its respective seeing. In the notebook 'fake-3d-maps-structure-function-analysis' there is the analysis of the structure functions results and their ratios of the non-smoothed/smoothed maps.

3. The current final results are at some extent consistent with the initial exploration where the effect of the seeing has decrease. As a comparison with the results of the 2D analysis, for values of seeing between 1-4 there is a decrease in the effect of the seeing for scales below r0. Above this value the results are consistent with the model we've been using. For values of seeing 8-32 the effect at small scales is less than the 2D maps but not as much as for values of 1-4. Above r0 there is a big discrepancy with what the model predicts and the current results. The behaviour of the apparent r0 is consistent between the 2D and 3D analysis.

![firefox_zdwOtMhd74](https://user-images.githubusercontent.com/53878105/215801676-a987e2d2-ce77-4df3-9b8e-9290d307c496.png)

4. Now that the pipeline and workflow are stablished I'll work on the pending queries by Dr. Will, continue with the analysis adding the fluctuating emissivity and meditate more about our current results.

**Comment by JavGVastro** [comment]
A couple of updates which may be of interest:

- Now that im working with an inhomogeneous denisity field the effects on the edges on the individual channels seem to have decreased in a consdeirable way, here some examples:

![firefox_fgbXoNgqq5](https://user-images.githubusercontent.com/53878105/216171073-43199663-4a98-4adc-a1a6-ada69183d20c.png)

![firefox_8VKAUO5wQg](https://user-images.githubusercontent.com/53878105/216171088-fcb15b09-a73f-4fd4-909e-4e8870affd84.png)

- Also, using an ihmogeneous density field, the slope of the both, tapered and non-tapered, structure function (periodic) have decreased. So maybe, this can be related to the projection smoothing (compare with the image above):

![firefox_QGVN4mQjVI](https://user-images.githubusercontent.com/53878105/216173118-32dfba3a-a21c-46f7-b703-95dade214725.png)

**Comment by will-henney** [comment]
Comment on the edge effects: we should make sure to use `boundary="fill"` in `convolve_fft()`

**Comment by will-henney** [comment]
Comment on the power law slopes:   I think we should maybe be using `2 + m` instead of `3 + m` for the slope of the power spectrum

But @JavGVastro should check this in the literature

**Comment by JavGVastro** [comment]
**Constant density case**

- In this case the index used for the 3D velocity field was k = 2 + 0.85 to recover a slope of m_2D = 1. 
- The density field is an homogeneous cube of 100 1/cm^3.
- The Figs. below are the 0th moment map and 1st moment map, and the fit to the respective B(r) (no seeing/periodic case).
- Finally there is an image of the seeing/non-periodic analysis.
- For seeing values with width below 4 pixels the model overestimate the reduction in B(r). For other seeing values and at a separation above 20 pixels the model underestimate the reduction. 
- For this analysis the seeing model parameter a = 0.75.

![firefox_ZfbNfyvceX](https://user-images.githubusercontent.com/53878105/218770069-a8fe97a2-1f37-499c-b490-7028e4a0e8c9.png)

![image434](https://user-images.githubusercontent.com/53878105/218771309-71e6eea8-6bee-4400-8c40-885f2bc7a040.png)

![firefox_YDYT0POugV](https://user-images.githubusercontent.com/53878105/218770163-caaff838-45e9-4888-9e8c-dcfa80f872b1.png)

**Comment by JavGVastro** [comment]
**Emissivity fluctuations case**

- In this case the index used for the 3D velocity and density fields were k = 3 + 0.55 to recover a slope of m_2D = 1. 
- The fluctuations in emissivity were obtained as E = ln(sig_E*density) where sig_E = 2 and sig_dens = 1.
- The Figs. below are the 0th moment map and 1st moment map, and the fit to the respective B(r) (no seeing/periodic case).
- Finally there is an image of the seeing/non-periodic analysis. 
- In this case the seeing model adjust better to the reduction in B(r) than for the constant density case.
- For this analysis the seeing model parameter a = 0.75.

![firefox_F5LOmpuf5N](https://user-images.githubusercontent.com/53878105/218772470-e5e1e828-63e8-461e-8dcb-cdafc9d26589.png)

![image470](https://user-images.githubusercontent.com/53878105/218772504-5adff52a-e747-4aa0-a7a2-8715445fee5a.png)

![firefox_ynBWHo3KTU](https://user-images.githubusercontent.com/53878105/218772539-2dfe44ec-cee0-4a99-9c1f-b3432ce629ac.png)

**Comment by JavGVastro** [comment]
Here is a summary of the case that is going to be used to update the paper. Also, there are the images files locations so everything can be easily found, tracked and reviewed.

**Emissivity fluctuations case: $\sigma_E = 1$**

- In this case the index used for the 3D velocity and density ($\rho$) fields was $n = 3 + 0.3$ ( to recover a slope of $m_{2D} = 1$, see below) and a $r_0 = 32$ pix.

- The fluctuations in emissivity were obtained as $E = \exp ( \sigma_E * \rho )$ where $\sigma_E = 1$ and $\sigma_{\rho} = 1$ (for the paper revision).

- The Figs. below are the 0th moment map and 1st moment map (tapered case).

![firefox_vwlxDr7eOO](https://user-images.githubusercontent.com/53878105/230966406-25389ebc-17ac-4bad-bf68-969b92ff1901.png)

Image file: _PhD.Paper/Fake-Maps/fake-3d-maps/sf-fake-3d-maps-emissivity-fluct_m1_sigE_1.ipynb_

-Comparison of the Initial structure functions of the 1st moment map.

![firefox_IfMfbxLd8B](https://user-images.githubusercontent.com/53878105/230968070-648387b6-3383-4b2f-a7c1-6a8009efc16f.png)

Image file: _PhD.Paper/Fake-Maps/fake-3d-maps/sf-fake-3d-maps-emissivity-fluct_m1_sigE_1.ipynb_

- Below is the fit to the respective $B(r)$ (non-seeing/periodic case) and confidence interval analysis to confirm that the spectrum from the previous point recovers a slope of $m_{2D} = 1$.

![Imagen sin título](https://user-images.githubusercontent.com/53878105/230967572-e34de691-13e8-4d3f-9e07-f9f59275cdbc.png)

Image file: _PhD.Paper/Fake-Maps/fake-3d-maps/ci-fake-3d-maps-emissivity-fluct_m1_sigE_1.ipynb_

- Finite box analysis.

Conclusion: The behaviour is shared as in the 2D case in the reduction of $\sigma$ and $r_0$ following the finite box analysis where the condition to recover $r_0$ is $\(L > 10 r_0\)$. The main difference is that the condition $\(L > 3 r_0\)$ to recover $r_0$ changes to $\(L > 5 r_0\)$ when applyting a fit to the results. The dashes line still is described by $1 - e^{L / x r_0}$ but with $x$ equal to $4.0$ instead of $3.6$ (2D maps).

![imagen](https://user-images.githubusercontent.com/53878105/230971484-c2e3e6ac-d664-456c-9261-5330327a3a76.png)

![imagen](https://user-images.githubusercontent.com/53878105/230971640-7b62c370-1389-4a10-b666-16dba56a439a.png)

![imagen](https://user-images.githubusercontent.com/53878105/230971684-bc423fb7-c243-4cb0-8879-6db549b1bc5b.png)

![imagen](https://user-images.githubusercontent.com/53878105/230971764-48e121b4-45f1-48e0-99a0-cba2cbcba7d1.png)

Images File: _PhD.Paper/Fake-Maps/fake-3d-maps/fake-3d-maps-finite-ems-fluct-SigE_1.ipynb_

-  Effects of seeing.

1. Create maps with their respective seeing:

![imagen](https://user-images.githubusercontent.com/53878105/230974064-21f4f8fb-bb99-47e0-b7fa-a7b31dbb09f8.png)

Image file: _PhD.Paper/Fake-Maps/fake-3d-maps/create-fake-3d-maps-seeing-nonp-ems-fluct-sigE_1.ipynb_

2. Compute structure functions.

File: _PhD.Paper/Fake-Maps/fake-3d-maps/sfs-fake-3d-maps-seeing-nonp-ems-fluc-sigE_1.ipynb_

3. Analysis on the reduction of $B(r)$ with respect differents s0.

The model changed from:

$S(r; s_0, r_0) = \frac{e^{-s_0 / r_0}}{1+(2s_0 / r)^{2a}}$ to

$S(r; s_0, r_0) = \left [ \left (1+\frac{1.25 s_0}{r_0} \right) \left(1+ \left (\frac{2.6 s_0}{r} \right) ^{2a} \right) \right ]^{-1}$

with $a = 0.75$

![imagen](https://user-images.githubusercontent.com/53878105/230974660-872f7dfe-e4fb-4522-a0e2-0fbcd7be4fcf.png)


Image file: _PhD.Paper/Fake-Maps/fake-3d-maps/fake-3d-maps-structure-function-analysis-ems-fluc_m4-sig_E_1.ipynb_

Note: The analysis of the new model is here: _PhD.Paper/Fake-Maps/fake-3d-maps/ratio_seeing_newmodel.ipynb_

**Comment by JavGVastro** [comment]
$S(r; s_0, r_0) = \left [ \left (1+a_1\frac{ s_0}{r_0} \right) \left(1+ \left (a_2 \frac{s_0}{r} \right) ^{a_3} \right) \right ]^{-1}$

* $\sigma_E = 0$
$a_1 = 1.35$, $a_2 =2.6 $, $a_3 = 1.5 $

![imagen](https://user-images.githubusercontent.com/53878105/233121734-2c8671d4-3f9e-4fd4-8701-97775db8ff76.png)

* $\sigma_E = 1$
$a_1 = 1.25$, $a_2 = 2.6$, $a_3 = 1.5$

![imagen](https://user-images.githubusercontent.com/53878105/233122302-f53598b1-f344-4907-9fcc-dd27d48484ec.png)

* $\sigma_E = 2$
$a_1 = 1.00$, $a_2 = 2.44$, $a_3 =1.7$

![imagen](https://user-images.githubusercontent.com/53878105/233122513-4c226b41-f165-48dc-b149-0b6ac8b0ad87.png)

Fake-Maps/fake-3d-maps/ratio_seeing_newmodel-global.ipynb
