### ISSUE TITLE
Last try to get the seeing to agree between NGC 595 and 604

### ISSUE THREAD

**Issue by will-henney** [JavGVastro/PhD.Paper#19]
I propose that we try an alternate fit to NGC 604 in which we give a very low weight to all the points with r > 20 pc. 

Hopefully, this would end up giving a fit like this (red line), which would be more similar to NGC 595:

![CleanShot 2023-04-21 at 19 00 12](https://user-images.githubusercontent.com/161264/233753603-fe846603-9ccf-4fcd-917b-b108ee378280.jpg)

Then the excess of the structure function around 60 pc could be due to a periodic oscillation with lambda = 120 pc, which would also explain the minimum B(r) at r = 120 pc. This would mean that the model sigma^2 would be significantly reduced because the periodic oscillation would contribute about half of the empirical sigma^2

We could include this in Appendix D, so it wouldn't make the paper any longer

**Comment by will-henney** [comment]
![CleanShot 2023-04-21 at 19 22 52](https://user-images.githubusercontent.com/161264/233754509-68095561-5671-4c5c-803c-7630eacebe02.jpg)

In fact, if you look at the velocity map, you can see what looks like a periodic pattern.  Of course, since the wavelength is similar to the size of the map, we cannot know if it is really periodic

**Comment by JavGVastro** [comment]
So, after some tweaks, I was able to obtain a better (and correct) fit of NGC 604 which takes into account the periodic oscillation. 

![image140](https://user-images.githubusercontent.com/53878105/234192217-8cf1dd4d-9690-4a59-918c-030ccc35ae2a.png)

Some notes:

1. The changes in the fit procedure were: 
a) the max $r$ for the fit was changed from $0.5 L_{\text{box}}$ to $0.7 L_{\text{box}}$. I found that the  parameters were more sensitive to the change in the range of $r$ than any other thing. 
b) The weights of the uncertainty were mainly used to adjust the reduced $\chi^{2}$, which in this case is: 0.95
c) in the prior the upper limit of $\sigma^2$ was reduced because of the dependancy of $B(r)_{\text{max}}$.

2. The red line the $B(r)$ from the first image is OK but at large scales it needs approach $2 \sigma^2$ which is the case for our results and follows the NGC 595 behaviour. I mention this because from the simulations we see:

![imagen](https://user-images.githubusercontent.com/53878105/234197699-719ccf3d-ee13-49b6-924e-3316f343b354.png)

which would be the case for the red line.
But assuming the results in this comment are correct we see another possibility of the periodic fluctuacions. Where as seen in the black circle in the image above we first encounter a concavity in $B(r)$ and the then a bump (as oppossed to the simulations, but maybe this just an artifact and changing the pattern, phase, etc., the ondulatios at the large scales of $B(r)$ can be changed).

3. The changes in the results are:

old (image first comment):
![imagen](https://user-images.githubusercontent.com/53878105/234201505-7dac7f59-cd7f-4e08-90c0-8957dc765372.png)
![imagen](https://user-images.githubusercontent.com/53878105/234201807-fbd18c1c-2885-42cb-b526-f8e7057a658f.png)

new (this comment image):
![imagen](https://user-images.githubusercontent.com/53878105/234201631-1247f3d8-2744-4d79-b38e-d8e20e491ef0.png)
![imagen](https://user-images.githubusercontent.com/53878105/234201856-46917f86-e4b5-4e68-abd3-1d8dbe08ac1e.png)

4. Some $p$-values increased:

previous:
![imagen](https://user-images.githubusercontent.com/53878105/234202161-c4864b0f-96d2-4705-8e64-c78fa6dfabc8.png)

new:
![imagen](https://user-images.githubusercontent.com/53878105/234202231-1c205f0c-8d61-4d5c-8d4c-a25ae2aa1700.png)

**Comment by will-henney** [comment]
[Edit: removed "not" from penultimate sentence]

Thanks for doing this.  That does look like a viable alternative model, but it is not quite what I was asking for.  I was suggesting something more extreme that would have a sig2 of about 40.  The idea was to only fit the part up to 20 pc.  Rather than using low weights, we could simply exclude all separations > 20 pc from the fit.

**Comment by will-henney** [comment]
A periodic oscillation must have an anti-correlation at r = lambda/2 (maximum in struc func) before it has a positive correlation at r = lambda (minimum in struc func). So the part you have circled on your new fit cannot be a periodic oscillation because the observed B(r) dips down below the model before rising above it. 

![CleanShot 2023-04-27 at 11 18 17@2x](https://user-images.githubusercontent.com/161264/234940235-4a8969cf-00c1-406b-9289-ff4f8de64640.jpg)

versus

![CleanShot 2023-04-27 at 11 21 42@2x](https://user-images.githubusercontent.com/161264/234940798-dd0f44fe-a254-4f77-b913-db1c7811c52d.jpg)

**Comment by will-henney** [comment]
But I am thinking that this is probably not important enough to delay the paper. What do you think?  We could just stay with what we have
